# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/main/protobuf/message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/main/protobuf/message.proto',
  package='protocols',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x1fsrc/main/protobuf/message.proto\x12\tprotocols\"a\n\x0bUserMessage\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\trecipient\x18\x03 \x01(\t\x12\x0e\n\x06sender\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\"7\n\x0fUserMessageList\x12$\n\x04list\x18\x01 \x03(\x0b\x32\x16.protocols.UserMessage\"6\n\x12UserMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\x08\"K\n\x13UserMessageResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.protocols.UserMessageResponseStatus\"X\n\x0b\x41uthMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12%\n\x05state\x18\x03 \x01(\x0e\x32\x16.protocols.ClientState\"F\n\x0c\x41uthResponse\x12\'\n\x08response\x18\x01 \x01(\x0e\x32\x15.protocols.AuthReturn\x12\r\n\x05token\x18\x02 \x01(\t\"4\n\x0bStateChange\x12%\n\x05state\x18\x01 \x01(\x0e\x32\x16.protocols.ClientState*T\n\x19UserMessageResponseStatus\x12\x0e\n\nMsgSuccess\x10\x00\x12\x0e\n\nMsgFailure\x10\x01\x12\x17\n\x13MsgRecipientUnknown\x10\x02*D\n\nAuthReturn\x12\x0f\n\x0b\x41uthSuccess\x10\x00\x12\x0f\n\x0b\x41uthFailure\x10\x01\x12\x14\n\x10\x41uthFailureRetry\x10\x02*c\n\x0b\x43lientState\x12\t\n\x05Setup\x10\x00\x12\n\n\x06Signup\x10\x01\x12\t\n\x05Login\x10\x02\x12\r\n\tMessaging\x10\x03\x12\x0b\n\x07Reading\x10\x04\x12\x0c\n\x08UserLoop\x10\x05\x12\x08\n\x04Quit\x10\x06\x42\x02P\x01\x62\x06proto3')
)

_USERMESSAGERESPONSESTATUS = _descriptor.EnumDescriptor(
  name='UserMessageResponseStatus',
  full_name='protocols.UserMessageResponseStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MsgSuccess', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MsgFailure', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MsgRecipientUnknown', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=551,
  serialized_end=635,
)
_sym_db.RegisterEnumDescriptor(_USERMESSAGERESPONSESTATUS)

UserMessageResponseStatus = enum_type_wrapper.EnumTypeWrapper(_USERMESSAGERESPONSESTATUS)
_AUTHRETURN = _descriptor.EnumDescriptor(
  name='AuthReturn',
  full_name='protocols.AuthReturn',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AuthSuccess', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AuthFailure', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AuthFailureRetry', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=637,
  serialized_end=705,
)
_sym_db.RegisterEnumDescriptor(_AUTHRETURN)

AuthReturn = enum_type_wrapper.EnumTypeWrapper(_AUTHRETURN)
_CLIENTSTATE = _descriptor.EnumDescriptor(
  name='ClientState',
  full_name='protocols.ClientState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Setup', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Signup', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Login', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Messaging', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Reading', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UserLoop', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Quit', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=707,
  serialized_end=806,
)
_sym_db.RegisterEnumDescriptor(_CLIENTSTATE)

ClientState = enum_type_wrapper.EnumTypeWrapper(_CLIENTSTATE)
MsgSuccess = 0
MsgFailure = 1
MsgRecipientUnknown = 2
AuthSuccess = 0
AuthFailure = 1
AuthFailureRetry = 2
Setup = 0
Signup = 1
Login = 2
Messaging = 3
Reading = 4
UserLoop = 5
Quit = 6



_USERMESSAGE = _descriptor.Descriptor(
  name='UserMessage',
  full_name='protocols.UserMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='protocols.UserMessage.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='protocols.UserMessage.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recipient', full_name='protocols.UserMessage.recipient', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='protocols.UserMessage.sender', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='protocols.UserMessage.content', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=143,
)


_USERMESSAGELIST = _descriptor.Descriptor(
  name='UserMessageList',
  full_name='protocols.UserMessageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='protocols.UserMessageList.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=200,
)


_USERMESSAGEREQUEST = _descriptor.Descriptor(
  name='UserMessageRequest',
  full_name='protocols.UserMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='protocols.UserMessageRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='protocols.UserMessageRequest.sender', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=256,
)


_USERMESSAGERESPONSE = _descriptor.Descriptor(
  name='UserMessageResponse',
  full_name='protocols.UserMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='protocols.UserMessageResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=333,
)


_AUTHMESSAGE = _descriptor.Descriptor(
  name='AuthMessage',
  full_name='protocols.AuthMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='protocols.AuthMessage.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='protocols.AuthMessage.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='protocols.AuthMessage.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=423,
)


_AUTHRESPONSE = _descriptor.Descriptor(
  name='AuthResponse',
  full_name='protocols.AuthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='protocols.AuthResponse.response', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='protocols.AuthResponse.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=495,
)


_STATECHANGE = _descriptor.Descriptor(
  name='StateChange',
  full_name='protocols.StateChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='protocols.StateChange.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=549,
)

_USERMESSAGELIST.fields_by_name['list'].message_type = _USERMESSAGE
_USERMESSAGERESPONSE.fields_by_name['status'].enum_type = _USERMESSAGERESPONSESTATUS
_AUTHMESSAGE.fields_by_name['state'].enum_type = _CLIENTSTATE
_AUTHRESPONSE.fields_by_name['response'].enum_type = _AUTHRETURN
_STATECHANGE.fields_by_name['state'].enum_type = _CLIENTSTATE
DESCRIPTOR.message_types_by_name['UserMessage'] = _USERMESSAGE
DESCRIPTOR.message_types_by_name['UserMessageList'] = _USERMESSAGELIST
DESCRIPTOR.message_types_by_name['UserMessageRequest'] = _USERMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['UserMessageResponse'] = _USERMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['AuthMessage'] = _AUTHMESSAGE
DESCRIPTOR.message_types_by_name['AuthResponse'] = _AUTHRESPONSE
DESCRIPTOR.message_types_by_name['StateChange'] = _STATECHANGE
DESCRIPTOR.enum_types_by_name['UserMessageResponseStatus'] = _USERMESSAGERESPONSESTATUS
DESCRIPTOR.enum_types_by_name['AuthReturn'] = _AUTHRETURN
DESCRIPTOR.enum_types_by_name['ClientState'] = _CLIENTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserMessage = _reflection.GeneratedProtocolMessageType('UserMessage', (_message.Message,), dict(
  DESCRIPTOR = _USERMESSAGE,
  __module__ = 'src.main.protobuf.message_pb2'
  # @@protoc_insertion_point(class_scope:protocols.UserMessage)
  ))
_sym_db.RegisterMessage(UserMessage)

UserMessageList = _reflection.GeneratedProtocolMessageType('UserMessageList', (_message.Message,), dict(
  DESCRIPTOR = _USERMESSAGELIST,
  __module__ = 'src.main.protobuf.message_pb2'
  # @@protoc_insertion_point(class_scope:protocols.UserMessageList)
  ))
_sym_db.RegisterMessage(UserMessageList)

UserMessageRequest = _reflection.GeneratedProtocolMessageType('UserMessageRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERMESSAGEREQUEST,
  __module__ = 'src.main.protobuf.message_pb2'
  # @@protoc_insertion_point(class_scope:protocols.UserMessageRequest)
  ))
_sym_db.RegisterMessage(UserMessageRequest)

UserMessageResponse = _reflection.GeneratedProtocolMessageType('UserMessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _USERMESSAGERESPONSE,
  __module__ = 'src.main.protobuf.message_pb2'
  # @@protoc_insertion_point(class_scope:protocols.UserMessageResponse)
  ))
_sym_db.RegisterMessage(UserMessageResponse)

AuthMessage = _reflection.GeneratedProtocolMessageType('AuthMessage', (_message.Message,), dict(
  DESCRIPTOR = _AUTHMESSAGE,
  __module__ = 'src.main.protobuf.message_pb2'
  # @@protoc_insertion_point(class_scope:protocols.AuthMessage)
  ))
_sym_db.RegisterMessage(AuthMessage)

AuthResponse = _reflection.GeneratedProtocolMessageType('AuthResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTHRESPONSE,
  __module__ = 'src.main.protobuf.message_pb2'
  # @@protoc_insertion_point(class_scope:protocols.AuthResponse)
  ))
_sym_db.RegisterMessage(AuthResponse)

StateChange = _reflection.GeneratedProtocolMessageType('StateChange', (_message.Message,), dict(
  DESCRIPTOR = _STATECHANGE,
  __module__ = 'src.main.protobuf.message_pb2'
  # @@protoc_insertion_point(class_scope:protocols.StateChange)
  ))
_sym_db.RegisterMessage(StateChange)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
